Create Artifacts works
dolittle-obsolete/cli pull request #22
Opened 2018-09-13 18:20 UTC by woksin

- ReadModel
- Event
- Command
- AggregateRoot

more to come later on.

Also fixes the Usage stuff for me at least.

Dependent on https://github.com/dolittle-boilerplates/ArtifactTemplates/pull/1

2018-09-13 18:38 UTC, einari requested changes
Wow.. Great stuff.  Pushing through a lot.  Have a couple of comments and we need to follow up a bit on some thoughts on how the context is thought to be used for different use cases - especially my comments around namespace is relevant in this case. Let's do that on a teams session tomorrow. 

On the topic of Specs; gonna be a bit hard on this. We're behind on it already and I'm working on catching up. That needs to be here before this PR can go in.

2018-09-13 18:38 UTC, einari commented on Source/artifacts/ArtifactsManager.js
> +    createAggregateRoot(name, namespace) {
Namespace should be deducted. 
Remember; namespace is a C# feature - and we can figure out what it is. As mentioned in the issue: https://github.com/dolittle-tools/cli/issues/8

Lets walk through a bit on context and what the thinking has been.

2018-09-13 18:38 UTC, einari commented on Source/dolittle-create-aggregateroot.js
> +    .example("dolittle create aggregateroot [name] [namespace]", "Creates an aggregate root with a given name and namespace in the current folder");
Namespace should be deducted. 
Remember; namespace is a C# feature - and we can figure out what it is. As mentioned in the issue: https://github.com/dolittle-tools/cli/issues/8

Lets walk through a bit on context and what the thinking has been.

2018-09-13 18:38 UTC, einari commented on Source/dolittle-create-event.js
> +    .example("dolittle create event [name] [namespace]", "Creates an event with a given name and namespace in the current folder");
Namespace should be deducted. 
Remember; namespace is a C# feature - and we can figure out what it is. As mentioned in the issue: https://github.com/dolittle-tools/cli/issues/8

Lets walk through a bit on context and what the thinking has been.

2018-09-13 18:38 UTC, einari commented on Source/dolittle-create-readmodel.js
> +    .example("dolittle create readmodel [name] [namespace]", "Creates a read model with a given name and namespace in the current folder");
Namespace should be deducted. 
Remember; namespace is a C# feature - and we can figure out what it is. As mentioned in the issue: https://github.com/dolittle-tools/cli/issues/8

Lets walk through a bit on context and what the thinking has been.

2018-09-13 18:38 UTC, einari commented on Source/dolittle-create-application.js
> +    .example(USAGE, "Creates an application with a given name");
Brilliant with examples !!

2018-09-22 07:19 UTC, einari reviewed
I've added the issue #34. `global.js`now has code specific to C#, which is not right. We need to go over the entire CLI and figure out a pattern for keeping language specific constructs isolated and also make sure its extensible and easy to add new languages without breaking the open/closed principle like we're doing now. Considering this technical debt.

2018-09-22 07:42 UTC, woksin commented
You're right, @einari. It's done this way just now to speed up the development, but I think that with enough metadata on the boilerplates it will be trivial to allow for extensibility while at the same time allow the actual code to be closed for modification.

2018-09-22 07:53 UTC, einari commented
Wow. There is a lot of features in the CLI right now. Really coming together. Looking great! 
I'm however going to block this pull request until there is a better spec coverage. 

This does not mean that we're aiming for 100% coverage. All the interaction bits, like the inquirers and things don't need to be specced out. But all the underlying services that are used to actually perform the operations need to. This is super important and something we don't want to compromise on.

2018-09-22 07:55 UTC, einari requested changes
Wow. There is a lot of features in the CLI right now. Really coming together. Looking great! Great work @woksin!
I'm however going to block this pull request until there is a better spec coverage.

This does not mean that we're aiming for 100% coverage. All the interaction bits, like the inquirers and things don't need to be specced out. But all the underlying services that are used to actually perform the operations need to. This is super important and something we don't want to compromise on.

2018-09-22 07:55 UTC, einari commented on Source/boilerPlates/BoilerPlate.js
> +        // TODO: Add options field
Register this as an issue instead of TODO in code - we don't want those

2018-09-22 07:55 UTC, einari commented on Source/boilerPlates/BoilerPlatesManager.js
> +        // TODO:
Register this as an issue instead of TODO in code - we don't want those

2018-09-22 07:55 UTC, einari commented on Source/global.js
> +    /**
Example of something that needs to be done for #34

2018-09-22 07:55 UTC, einari commented on Source/global.js
> +    createCSharpNamespace(currentPath, csprojPath) {
Missing Specs for this as far as I can see.

2018-09-22 07:55 UTC, einari commented on Source/global.js
> +            console.log('segmentPath: ', segmentPath);
Should not be using `console.log()` - use the logger

2018-09-22 07:55 UTC, einari commented on Source/global.js
> +        let currentPath = process.cwd();
I know this is changed in a later commit - but want to point out; using `process` directly like this makes it virtually impossible to consistently create tests for it. Which leads me to; there are to specs for this :)

2018-09-22 07:55 UTC, einari commented on Source/artifacts/QueryforInquirer.js
> +            {
An example of something needing to be dealt with for #34. We should be able to feed language specific queries from a different place. Namespace is C# specific and should be somewhere else.

2018-09-22 07:55 UTC, einari commented on Source/artifacts/QueryforInquirer.js
> +    _findCSharpReadmodels() {
An example of something for #34

2018-09-22 07:55 UTC, einari commented on Source/artifacts/AggregateRootInquirer.js
> +    _getCSharpPrompt() {
An example of something for #34

2018-09-22 07:55 UTC, einari commented on Source/artifacts/ArtifactsManager.js
>          let destination = process.cwd();
Using `process` directly will make automated specs virtually impossible to write consistently. I suggest introducing a context object that can can be taken dependencies on and set up during globals setup. In it we could have the current working directory as a propery.

2018-09-22 07:55 UTC, einari commented on Source/artifacts/ArtifactsManager.js
>          let destination = process.cwd();
Using process directly will make automated specs virtually impossible to write consistently. I suggest introducing a context object that can can be taken dependencies on and set up during globals setup. In it we could have the current working directory as a propery.

2018-09-22 07:55 UTC, einari commented on Source/artifacts/EventInquirer.js
> +    _getCSharpPrompt() {
An example for #34

2018-09-22 07:55 UTC, einari commented on Source/artifacts/ReadModelInquirer.js
> +    _getCSharpPrompt() {
An example for #34

2018-09-22 07:55 UTC, einari commented on Source/artifacts/ReadModelInquirer.js
> +        const namespace = global.createCSharpNamespace(process.cwd(), global.getNearestCsprojFile());
Using process directly will make automated specs virtually impossible to write consistently. I suggest introducing a context object that can can be taken dependencies on and set up during globals setup. In it we could have the current working directory as a propery.

2018-09-22 07:55 UTC, einari commented on Source/artifacts/AggregateRootInquirer.js
> +    _getCSharpPrompt(name) {
Example for #34

2018-09-22 07:55 UTC, einari commented on Source/artifacts/ArtifactsManager.js
> +    createQueryFor(flags) {
Terminology; flags is typical bits / booleans one turns on and off. I'd switch to something like context.

2018-09-22 07:55 UTC, einari commented on Source/artifacts/CommandInquirer.js
> +        if (flags.language === 'csharp') {
Lets figure out a way to not have to have an if/else pattern for adding new languages. Relates to #34. 
We need something like an interface for the things that we want to provide language specific things for and register every language specific implementation at startup. We could then have a context object which would then hold a reference to instances of these. 

Btw: Flags -> context

2018-09-22 07:55 UTC, einari commented on Source/artifacts/EventInquirer.js
> +        let questions = cSharpInquirer.getCSharpQuestions();
Example for #34

2018-09-22 07:55 UTC, einari commented on Source/artifacts/InquirerManager.js
> +    promptForCommand(flags) {
flags -> context

2018-09-22 07:55 UTC, einari commented on Source/artifacts/InquirerManager.js
> +    promptForEvent(flags) {
flags -> context

2018-09-22 07:55 UTC, einari commented on Source/artifacts/InquirerManager.js
> +    promptForReadModel(flags) {
flags -> context

2018-09-22 07:55 UTC, einari commented on Source/artifacts/QueryInquirer.js
> +    _getCSharpPrompt(name) {
Example for #34

2018-09-22 07:55 UTC, einari commented on Source/artifacts/ReadModelInquirer.js
> +    _getCSharpPrompt(name) {
Example for #34

2018-09-22 07:55 UTC, einari commented on Source/artifacts/ArtifactsManager.js
>      createCommand(flags) {
flags -> context

2018-09-22 07:55 UTC, einari commented on Source/artifacts/EventProcessorInquirer.js
> +    _findCSharpEvents() {
Example for #34

2018-09-22 07:55 UTC, einari commented on Source/boilerPlates/BoilerPlatesManager.js
> +            process.exit(1);
This would break automated specs dramatically

2018-09-22 07:55 UTC, einari commented on Source/artifacts/CommandHandlerInquirer.js
> +    _findCSharpCommands() {
Example for #34

2018-09-22 07:55 UTC, einari commented on Source/artifacts/EventProcessorInquirer.js
>      _getCSharpPrompt(name) {
Example for #34

2018-09-22 08:01 UTC, woksin commented
Of course, @einari. Once I've nailed down most of the features of the artifacts and maybe done some fine tuning. then Specs will be the first thing on my list. 😉

2018-09-22 08:04 UTC, einari commented
May I suggest doing it for the things that are in place now so that we can close this pull request before it becomes too big.

2018-09-26 14:30 UTC, closed without merging